[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_logger = { path = "../../", features=["panic"]}
flutter_rust_bridge = "=2.0.0-dev.27"
log = "0.4.19"
