[package]
name = "flutter_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flutter_rust_bridge = "1.78.0"
once_cell = "1.18.0"

[features]
panic = []
